{% set version = "0.8.7" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-reshape
  version: {{ version|replace("-", "_") }}

source:
  fn: reshape_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/reshape_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/reshape/reshape_{{ version }}.tar.gz
  sha256: 2fa6c87d1e89f182e51bc5a4fcda3d42d83b8fb4474ca525fa7a8db5081f3992

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - r-base
    - r-plyr
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-plyr
    - libgcc  # [not win]

test:
  commands:
    - $R -e "library('reshape')"  # [not win]
    - "\"%R%\" -e \"library('reshape')\""  # [win]

about:
  home: http://had.co.nz/reshape
  license: MIT
  summary: Flexibly restructure and aggregate data using just melt() and cast().
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
