appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  linux_aarch64: default
  linux_ppc64le: azure
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: mLX+a6jTXauYPdAx5jJttYTuz/0vxWV9pXjXx+znmkh4bGgIr8iyTH1L6XD7uYk7c4koEWM4JCOEVAN2xcVn5YYR9uq0o2gMcZe9+Mh3WEbsM/qc0lMJBMayWlvSQViB2YJ11NYtf9bgurSXfxg6uddJkQLubidS6pf0RrKacyXCZ3Mf8cVIsKFcebnCgJoY9u444LB6JqQ0gocflhdxEv2yyu1CnImN1jQ20hww6R+ZSWSQYxV23UxV2xCMo+CL3PjvuAbdSUGwV2AwzE6xhxQ3XGlEsh8zdThwIxL/BS8XR0oeclB6nUi4xUTP6+QbTLtTVifQNAn5adzuDAjmUMKq+qTzhj2rlDgoLZSbuyppf8VSgiItZzCRrk/l+1lrcCdGoRIDWjZ3jbxCiWmpUtqlZFSKZqj+WsZ7+Kfv9MXNVJR4SlW6qigRFEMV+pJPkuZe8zEifBCjlN8q6R9YZrnOWrbej8ZP5gbxGgNTrhRLB1+Rs8rSEhYboBokYRKMPy1giwCB0XcWXfAoJutuL5khpWuIfMvz5luzolb2kyW4lQHPpHzWOA8wd5rBRL9469kbfctvRCD47khju712RGLi4ki/z1R+XIgDbiWhXNhDPabEolzFKlAGW0J5R2zR2j2mbNYjNxWfmEIMJqKjlI2hShvaRfR8scMLhRa9h5k=
